// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Activity_Order_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Activity_Order_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201408201249341_Activity_Order_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
